### ISSUE TITLE
【报错】文件缺失

### ISSUE THREAD

**Issue by Agnes4m** [bridgeL/nonebot-plugin-ayaka-games#2]
**ubuntu20.04,python3.10.6,nonebot2.0.0b5**
如下文件缺失，git clone里面没有这个文件
### 启动报错
![image](https://user-images.githubusercontent.com/70925546/198433659-d07adf9d-e58a-46e6-a9bf-0f6987e65123.png)
### 启动后报错
```
10-28 09:17:14 [SUCCESS] ayaka | 触发定时任务 bili_dy
Task exception was never retrieved
future: <Task finished name='Task-158' coro=<handle() done, defined at /usr/local/lib/python3.10/site-packages/ayaka_games/bili_dy.py:103> exception=IsADirectoryError(21, 'Is a directory')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ayaka_games/bili_dy.py", line 105, in handle
    up_list = load()
  File "/usr/local/lib/python3.10/site-packages/ayaka_games/bili_dy.py", line 48, in load
    return _UpList(value=uid_file.load())
  File "/usr/local/lib/python3.10/site-packages/ayaka/ayaka.py", line 525, in load
    with self.path.open("r", encoding="utf8") as f:
  File "/usr/local/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
IsADirectoryError: [Errno 21] Is a directory: 'data/plugins/bili_dy/uids'
```

**Comment by bridgeL** [comment]
我后续给插件删改了一些功能，你试着卸载以后安装 nonebot-plugin-ayaka-games==0.2.1 版本呢？

我删除了原来的b站动态更新功能，目前正在写一个方法过滤一些up的广告动态，等做完了之后会发新版

原来的 原神接龙 和 成语接龙 逻辑相似，现在合成一个接龙功能了，而且可以用户自行添加新的词库，详见 data/plugins/接龙文件夹
