### ISSUE TITLE
如何卸载插件呢

### ISSUE THREAD

**Issue by Agnes4m** [bridgeL/nonebot-plugin-ayaka-games#3]
用命令nb plugin uninstall nonebot-plugin-ayaka-games
```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/shutil.py", line 815, in move
    os.rename(src, real_dst)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.10/site-packages/ayaka_games/' -> '/tmp/pip-uninstall-_h77pqvf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/commands/uninstall.py", line 98, in run
    uninstall_pathset = req.uninstall(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/req/req_install.py", line 660, in uninstall
    uninstalled_pathset.remove(auto_confirm, verbose)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/req/req_uninstall.py", line 373, in remove
    moved.stash(path)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/req/req_uninstall.py", line 271, in stash
    renames(path, new_path)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/pip/_internal/utils/misc.py", line 311, in renames
    shutil.move(old, new)
  File "/usr/local/lib/python3.10/shutil.py", line 833, in move
    rmtree(src)
  File "/usr/local/lib/python3.10/shutil.py", line 724, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/lib/python3.10/shutil.py", line 680, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/lib/python3.10/shutil.py", line 678, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'dragon.py'
```

**Comment by bridgeL** [comment]
用的是哪个版本的？`pip list | grep ayaka`看一下版本，当前版本是0.3.3，恐怕卸载失败是旧版本导致的？

**通过pip卸载（推荐）**
`pip uninstall nonebot-plugin-ayaka-games`

**手动删除方法（有点麻烦）：**

`ls /home/ubuntu/.local/lib/python3.10/site-packages | grep ayaka`看一下文件夹是否存在

如果存在则可以`cd /home/ubuntu/.local/lib/python3.10/site-packages`，去手动删除`ayaka`和`ayaka_games`文件夹，以及它们对应的`.dist-info`文件夹

**Comment by bridgeL** [comment]
是否已解决问题呢？

**Comment by Agnes4m** [comment]
手动删除了，可以了
