### ISSUE TITLE
 No module named 'venv.virtualenvs'和 playwright未加载，win平台请关闭fastapi reload功能问题

### ISSUE THREAD

**Issue by Ugarei** [bridgeL/nonebot-plugin-ayaka-games#8]

**Comment by Ugarei** [comment]
这两个功能要怎么关闭？

**Comment by Ugarei** [comment]
No module named 'venv.virtualenvs'，而实际上这个 'virtualenvs'已经在venv文件里面了，这是什么问题？

**Comment by bridgeL** [comment]
1. No module named 'venv.virtualenvs'可以提供一下完整的报错截图吗？

2. playwright未加载，win平台请关闭fastapi reload功能问题

这是由于playwright无法在windows平台上与fastapi的reload功能同时开启

有两种解决方法：

第一种，关闭reload：修改.env.dev，`fastapi_reload=false`

第二种，关闭playwright：修改ayaka源码，找到（以我的电脑为例）`C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Lib\site-packages\ayaka`文件夹，（你可以通过` pip show nonebot-plugin-ayaka`命令查看ayaka安装位置）

替换`playwright.py`中的内容为
```py
print("！！！注意，此为ayaka临时运行解决方案！！！") #如果你不喜欢提示，就删了这句
async def get_new_page(width=None, high_quality=False, **kwargs):
    pass
async def init_chrome():
    pass
async def close_chrome():
    pass
```

**Comment by Ugarei** [comment]
11-30 10:03:19 [ERROR] ayaka_games | 导入失败 who_is_suspect
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\.\bot.py", line 84, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\ayaka_games\__init__.py", line 25, in <module>
    import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'venv.virtualenvs'

**Comment by bridgeL** [comment]
我对virtualenv不熟，你的插件都是装在virtualenv的虚拟环境中吗？如果可以的话，不使用虚拟环境会报错吗

**Comment by bridgeL** [comment]
可能是在导入的时候包名有错误

`pip show nonebot-plugin-ayaka-games`

修改ayaka_games源码，将`__init__.py`替换为

```py
# 导入全部插件
from .plugins.bag import *
from .plugins.bili import *
from .plugins.calc_24 import *
from .plugins.checkin import *
from .plugins.cy_query import *
from .plugins.get_30 import *
from .plugins.incan import *
from .plugins.mana import *
from .plugins.nbnhhsh import *
from .plugins.plus_one import *
from .plugins.reminder import *
from .plugins.who_is_suspect import *
```

**Comment by bridgeL** [comment]
ayaka的下一个版本将提供playwright开启/关闭的配置项，ayaka_games的下一个版本将修改__init__.py中导入子插件的方式，届时将无需修改源码修复问题

感谢反馈

**Comment by Ugarei** [comment]
按照您说的去做了，确实改正了很多问题，但是No module named 'venv.virtualenvs'还是在报错，这个错是找不到'venv.virtualenvs'这个东西，而我检查了一些，我只有virtualenvs这个，但是 'venv.virtualenvs'这个东西我还是真没有，这个东西有什么安装途径吗？

**Comment by bridgeL** [comment]
可以看下现在的报错吗，我一会也用一下virtualenvs试试

**Comment by Ugarei** [comment]
11-30 10:57:17 [ERROR] ayaka_games | 导入失败 who_is_suspect
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\.\bot.py", line 84, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 168, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\ayaka_games\__init__.py", line 37, in <module>
    import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'venv.virtualenvs'

**Comment by Ugarei** [comment]
playwright已经可以正常进行了，就是游戏还是导不进去

**Comment by bridgeL** [comment]
把这个文件File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\ayaka_games_init_.py"的内容也按照

```py
# 导入全部插件
from .plugins.bag import *
from .plugins.bili import *
from .plugins.calc_24 import *
from .plugins.checkin import *
from .plugins.cy_query import *
from .plugins.get_30 import *
from .plugins.incan import *
from .plugins.mana import *
from .plugins.nbnhhsh import *
from .plugins.plus_one import *
from .plugins.reminder import *
from .plugins.who_is_suspect import *
```
进行替换吧

**Comment by Ugarei** [comment]
刚才就是在这个文件里面替换的

**Comment by Ugarei** [comment]
报错变了
11-30 11:08:16 [ERROR] nonebot | Failed to import "ayaka_games"
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\.\bot.py", line 84, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 172, in load_all_plugins
    return set(
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 144, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\nonebot\plugin\manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\moral leader\nonebot2-oneclick-win-main\venv\virtualenvs\nb2-oneclick-Q7LARi9u-py3.10\lib\site-packages\ayaka_games\__init__.py", line 14, in <module>
    work_path = Path.cwd().absolute()
NameError: name 'Path' is not defined

**Comment by bridgeL** [comment]
好吧，看来问题很麻烦，你可以先卸载我的插件，等晚上我发布新版本应该能解决这些问题

**Comment by Ugarei** [comment]
谢谢——您真是太有耐心了，上次我这么蠢的时候被一个大佬骂了一回

**Comment by bridgeL** [comment]
我也在边学边写，一起进步哈，感谢所有issue

**Comment by bridgeL** [comment]
新版本已发布 `pip install nonebot-plugin-ayaka-games==0.3.6`
